version: "3.8"

services:  
  # Proxy to container
  whoami0:
    image: containous/whoami
    container_name: whoami0
    networks:
      - caddy_proxy
    labels:
      caddy: whoami0.example.com
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: "internal"
      caddy.tls.on_demand:

  # TODO figure out how to use legit CA
  # Proxy to service that you want to expose to the outside world
  whoami1:
    image: containous/whoami
    container_name: whoami1
    networks:
      - caddy_proxy
    labels:
      caddy: whoami1.example.com
      caddy.reverse_proxy: "{{upstreams 80}}"
      # remove the following line when you have verified your setup
      # Otherwise you risk being rate limited by let's encrypt
      caddy.tls.ca: https://acme-staging-v02.api.letsencrypt.org/directory

networks:
  caddy_proxy:
    external: true