version: "3.8"

services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - UMASK_SET=022 #optional
    volumes:
      - config:/config
      - tv:/tv
      - downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - caddy_proxy
    labels:
      caddy: sonarr.example.com
      caddy.reverse_proxy: "{{upstreams 8989}}"
      caddy.tls: "internal"
      caddy.tls.on_demand:

networks:
  caddy_proxy:
    external: true

volumes:
  config:
  tv:
  downloads: