version: "3.8"

services:
  bazarr:
    image: linuxserver/bazarr
    environment:
      PUID: ${BAZARR_PUID}
      PGID: ${PGID}
      UMASK: ${UMASK}
      TZ: ${TZ}
    volumes:
      - bazarr_config:/config
      - bazarr_data:/data
    networks:
      - proxy
    deploy:
      placement:
        constraints: [node.hostname == beluga]
      labels:
        caddy: bazarr.ant-podz.xyz
        caddy.reverse_proxy: "{{upstreams 6767}}"
        caddy.tls: internal
        caddy.tls.on_demand:

networks:
  proxy:
    external: true

volumes:
  bazarr_config:
  bazarr_data:
    driver: local
    driver_opts:
      type: nfs4
      o: ${NFS_CONN}
      device: :/data