version: "3.8"

services:
  caddy:
    image: homeall/caddy-reverse-proxy-cloudflare:latest
    environment:
      CADDY_INGRESS_NETWORKS: proxy
      TZ: ${TZ}
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data  # this volume is needed to keep the certificates otherwise, new ones will be re-issued upon restart
    labels: # Global options
      caddy.email: ${LETSENCRYPT_EMAIL}
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  proxy:
    external: true
          
volumes:
  caddy_data:
#     driver: local
#     driver_opts:
#       type: nfs4
#       o: ${NFS_CONN}
#       device: :/docker/caddy