version: "3.8"

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci
    env_file: .env
    environment:
      - CADDY_INGRESS_NETWORKS=proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data  # this volume is needed to keep the certificates otherwise, new ones will be re-issued upon restart
    labels: # Global options
      caddy.email: dttztceclomabxpzit@kiabws.online
    deploy:
      placement:
        constraints: [node.role == manager] #TODO move?

networks:
  proxy:
    external: true
          
volumes:
  caddy_data:
    driver: local
    driver_opts:
      type: nfs
      o: $NFS_CONN
      device: :/docker/caddy