version: "3.8"

# TODO https://github.com/go-gitea/gitea/issues/531
services:
  gitea:
    image: kunde21/gitea-arm
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "3000:3000"
      - "222:22"
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - gitea:/data
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    deploy:
      labels:
        caddy: gitea.example.com
        caddy.reverse_proxy: "{{upstreams 3000}}"
        caddy.tls: "internal"
        caddy.tls.on_demand:

volumes:
  gitea:
    driver: local
    driver_opts:
      type: "nfs"
      o: "vers=4,port=2049,addr=192.168.0.201,rw"
      device: ":/gitea/data"

networks:
  proxy:
    external: true