version: "3.8"

# TODO https://github.com/go-gitea/gitea/issues/531
services:
  gitea:
    image: kunde21/gitea-arm
    env_file: .env
    ports:
      - "3000:3000"
      - "222:22"
    environment:
      USER_UID: $UID
      USER_GID: $GID
    networks:
      - proxy
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    deploy:
      labels:
        caddy: gitea.example.com
        caddy.reverse_proxy: "{{upstreams 3000}}"
        caddy.tls: "internal"
        caddy.tls.on_demand:

networks:
  proxy:
    external: true

volumes:
  gitea-data:
    driver: local
    driver_opts:
      type: "nfs"
      o: $NFS_CONN
      device: ":/gitea/data"