version: "3.8"

# https://askubuntu.com/questions/525243/why-do-i-get-wrong-fs-type-bad-option-bad-superblock-error
services:
  nfs-server:
    image: gists/nfs-server
    container_name: nfs-server
    env_file: .env
    privileged: true # cant run this in swarm mode :(
    # networks:
    #   - proxy
    ports:
      - "2049:2049"
    # https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities
    cap_add:
      - SYS_ADMIN
      - SETPCAP
    environment:
      TZ: $TZ
      NFS_OPTION: 'fsid=0,rw,sync,insecure,no_subtree_check,nohide,no_root_squash' ## use userid
      # NFS_DOMAIN: "*" # The visitor IP range
    volumes:
      - /docker/data:/nfs-share
    restart: always

# networks:
#   proxy:
#     external: true