version: '3.8'

services:
  overseerr:
    image: linuxserver/overseerr
    environment:
      PUID: ${OVERSEERR_PUID}
      PGID: ${PGID}
      UMASK: ${UMASK}
      TZ: ${TZ}
    volumes:
      - /home/docker/overseerr:/config
    networks:
      - proxy
    deploy:
      placement:
        constraints: [node.hostname == vaquita]
      labels:
        caddy: overseerr.ant-podz.xyz
        caddy.reverse_proxy: "{{upstreams 5055}}"
        caddy.tls.dns: "cloudflare ${CLOUDFLARE_TOKEN}"
        caddy.tls.resolvers: 1.1.1.1

networks:
  proxy:
    external: true