version: "3.8"

services:
  pihole:
    image: pihole/pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # dhcp
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${PIHOLE_PASS}
      PIHOLE_DNS_: 10.0.6.6#53;1.1.1.1 #TODO, how to populate with unbound container ip?
      TEMPERATUREUNIT: f
    networks:
      - proxy
      - dns
    # Volumes store your data between container upgrades
    volumes:
      - etc_pihole:/etc/pihole/
      - etc_dnsmasqd:/etc/dnsmasq.d/
      # run `touch ./pihole.log` first unless you like errors
      # - ./pihole.log:/var/log/pihole.log
    deploy:
      placement:
        constraints: [node.hostname == beluga]
      labels:
        caddy: pihole.ant-podz.xyz
        caddy.reverse_proxy: "{{upstreams 80}}" #forwarding 443 breaks the web ui?
        caddy.tls: internal
        caddy.tls.on_demand:

networks:
  proxy:
    external: true
  dns:
    external: true

volumes:
  etc_pihole:
    driver: local
    driver_opts:
      type: nfs4
      o: ${NFS_CONN}
      device: :/docker/pihole/etc_pihole
  etc_dnsmasqd:
    driver: local
    driver_opts:
      type: nfs4
      o: ${NFS_CONN}
      device: :/docker/pihole/etc_dnsmasqd