version: "3.8"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8053:80/tcp"
      - "8054:443/tcp"
    environment:
      TZ: 'America/Denver'
      WEBPASSWORD: 'temp123' #TODO secrets
      DNS1: 127.0.0.1
      DNS2: 9.9.9.9
      FTL_CMD: debug
      DNSMASQ_LISTENING: all
    # Volumes store your data between container upgrades
    volumes:
      - etc-pihole:/etc/pihole/
      - etc-dnsmasqd:/etc/dnsmasq.d/
      # run `touch ./pihole.log` first unless you like errors
      # - ./pihole.log:/var/log/pihole.log
    deploy:
      labels:
        caddy: pihole.example.com
        caddy.reverse_proxy: "{{upstreams 80}}"
        caddy.tls: "internal"
        caddy.tls.on_demand:

volumes:
  etc-pihole:
    driver: local
    driver_opts:
      type: "nfs"
      o: "vers=4,port=2049,addr=192.168.0.201,rw"
      device: ":/pihole/etc-pihole"
  etc-dnsmasqd:
    driver: local
    driver_opts:
      type: "nfs"
      o: "vers=4,port=2049,addr=192.168.0.201,rw"
      device: ":/pihole/etc-dnsmasqd"

networks:
  proxy:
    external: true