version: "3.8"

# http://jell.yfish.us/
# https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/
services:
  plex:
    image: plexinc/pms-docker
    # ports:
    #   - 32400:32400
    networks:
      - proxy
    environment:
      - PLEX_UID=${PLEX_PUID}
      - PLEX_GID=${PGID}
      - ADVERTISE_IP=${ADVERTISE_IP}
      - TZ=${TZ}
      - PLEX_CLAIM= #optional
      # - 'ALLOWED_NETWORKS=192.168.1.0/24,172.16.0.0/12'
    volumes:
      - plex_config:/config
      - /media/nas1/data/media:/media
    deploy:
      placement:
        constraints: [node.hostname == humpback]
      labels:
        caddy: plex.ant-podz.xyz
        caddy.reverse_proxy: "{{upstreams 32400}}"
        caddy.tls.dns: "cloudflare ${CLOUDFLARE_TOKEN}"
        caddy.tls.resolvers: 1.1.1.1

networks:
  proxy:
    external: true         

volumes:
  plex_config:
  # plex_media:
  #   driver: local
  #   driver_opts:
  #     type: nfs4
  #     o: ${NFS_CONN}
  #     device: :/data/media