version: "3.8"

# http://jell.yfish.us/
# https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/
services:
  plex:
    image: plexinc/pms-docker
    env_file: .env
    ports:
      - 32400:32400
    networks:
      - proxy
    environment:
      - PLEX_UID=1000
      - PLEX_GID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
      - 'ADVERTISE_IP=http://$HUMPBACK:32400/,https://plex.example.com/'
    volumes:
      - plex_config:/config
      # - plex_tv:/tv
      - plex_movies:/data
    deploy:
      placement:
        constraints: [node.hostname == humpback]
      labels:
        caddy: plex.example.com
        caddy.reverse_proxy: "{{upstreams 32400}}"
        caddy.tls: "internal"
        caddy.tls.on_demand:

networks:
  proxy:
    external: true         

volumes:
  plex_config:
    driver: local
    driver_opts:
      type: "nfs"
      o: $NFS_CONN
      device: ":/plex/config"
  plex_tv:
    driver: local
    driver_opts:
      type: "nfs"
      o: $NFS_CONN
      device: ":/plex/tv"
  plex_movies:
    driver: local
    driver_opts:
      type: "nfs"
      o: $NFS_CONN
      device: ":/plex/movies"