version: '3.8'

#TODO reconfigure login
services:
  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    # ports:
      # - "8000:8000" #https://documentation.portainer.io/v2.0/deploy/edgeagent/
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
      - proxy
    deploy:
      labels:
        caddy: portainer.lan.com
        caddy.reverse_proxy: "{{upstreams 9000}}"
        caddy.tls: "internal"
        caddy.tls.on_demand:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  agent_network:
    driver: overlay
    attachable: true
  proxy:
    external: true

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: nfs
      o: $NFS_CONN
      device: :/docker/portainer