version: "3.8"

services:
  prowlarr:
    image: linuxserver/prowlarr:develop
    env_file: .env
    environment:
      PUID: $UID
      PGID: $GID
      TZ: $TZ
    volumes:
      - prowlarr_config:/config
    networks:
      - proxy
    deploy:
      placement:
        constraints: [node.role == worker]
      labels:
        caddy: prowlarr.lan.com
        caddy.reverse_proxy: "{{upstreams 9696}}"
        caddy.tls: "internal"
        caddy.tls.on_demand:

networks:
  proxy:
    external: true

volumes:
  prowlarr_config:
    driver: local
    driver_opts:
      type: nfs
      o: $NFS_CONN
      device: :/docker/prowlarr
