version: "3.8"

services:
  qbittorrent-openvpn:
    image: guillaumedsde/alpine-qbittorrent-openvpn:latest
    env_file: 
      - .env
    ports:
      - "8055:8080"
    environment:
      OPENVPN_PROVIDER: MULLVAD
      OPENVPN_CONFIG: default
      # OPENVPN_USERNAME: $MULLVAD_USER
      # OPENVPN_PASSWORD: $MULLVAD_PW
      PUID: $UID
      PGID: $GID
      LAN: 192.168.0.1/24 #todo
    networks:
      - proxy
    volumes:
      - qbittorrent_config:/config
      - qbittorrent_downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    labels:
      caddy: qbittorent.example.com
      caddy.reverse_proxy: "{{upstreams 8080}}"
      caddy.tls: "internal"
      caddy.tls.on_demand:
    cap_add:
      - NET_ADMIN

networks:
  proxy:
    external: true

volumes:
  qbittorrent_config:
    driver: local
    driver_opts:
      type: "nfs"
      o: $NFS_CONN
      device: ":/qbittorrent/config"
  qbittorrent_downloads:
    driver: local
    driver_opts:
      type: "nfs"
      o: $NFS_CONN
      device: ":/qbittorrent/downloads"