version: "3.8"

# https://github.com/haugene/docker-transmission-openvpn/issues/847
services:
  qbittorrent-openvpn:
    image: guillaumedsde/alpine-qbittorrent-openvpn
    container_name: qbittorrent
    # privileged: true
    cap_add:
      - NET_ADMIN
    # sysctls:
    #   - net.ipv6.conf.all.disable_ipv6=0
    env_file: 
      - .env
    environment:
      # OPENVPN_PROVIDER: MULLVAD
      # OPENVPN_CONFIG: default
      # OPENVPN_USERNAME: $MULLVAD_USER
      # OPENVPN_PASSWORD: $MULLVAD_PW
      # PUID: $UID
      # PGID: $GID
      # LAN: 192.168.0.0/24 # actual lan network subnet
      LAN: 10.0.2.0/24 # proxy overlay netowkr subnet
    networks:
      - proxy
    volumes:
      - qbittorrent_config:/config
      - qbittorrent_downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    labels:
      caddy: qbittorrent.example.com
      caddy.reverse_proxy: "{{upstreams 8080}}"
      caddy.reverse_proxy.header_upstream X-Forwarded-Host: {host}:443
      # caddy.reverse_proxy.header_upstream -Origin: 
      # caddy.reverse_proxy.header_upstream -Referer: 
      caddy.tls: "internal"
      caddy.tls.on_demand:

networks:
  proxy:
    external: true

volumes:
  qbittorrent_config:
    driver: local
    driver_opts:
      type: "nfs"
      o: $NFS_CONN
      device: ":/qbittorrent/config"
  qbittorrent_downloads:
    driver: local
    driver_opts:
      type: "nfs"
      o: $NFS_CONN
      device: ":/qbittorrent/downloads"