version: "3.8"
services:
  qbittorrent-openvpn:
    image: guillaumedsde/alpine-qbittorrent-openvpn:latest
    env_file: .env
    ports:
      - "8055:8080"
    environment:
      OPENVPN_PROVIDER: MULLVAD
      OPENVPN_CONFIG: default
      OPENVPN_USERNAME: $MULLVAD_USER
      OPENVPN_PASSWORD: $MULLVAD_PW
      PUID: $UID
      PGID: $GID
      LAN: 10.10.30.0/24 #todo
    networks:
      - proxy
    volumes:
      - qbittorrent-downloads:/downloads
      - qbittorrent-config:/config
      - /etc/localtime:/etc/localtime:ro
    deploy:
      labels:
        caddy: qbittorent.example.com
        caddy.reverse_proxy: "{{upstreams 8080}}"
        caddy.tls: "internal"
        caddy.tls.on_demand:
    cap_add:
      - NET_ADMIN # not sure if this works with swarm

networks:
  proxy:
    external: true

#todo update with external
volumes:
  qbittorrent-downloads:
    driver: local
    driver_opts:
      type: "nfs"
      o: $NFS_CONN
      device: ":/pihole/etc-pihole"
  qbittorrent-config:
    driver: local
    driver_opts:
      type: "nfs"
      o: $NFS_CONN
      device: ":/pihole/etc-dnsmasqd"