version: "3.8"
services:
  qbittorrent-openvpn:
    image: guillaumedsde/alpine-qbittorrent-openvpn:latest
    # volumes:
      # - "/your/storage/path/:/downloads"
      # - "/path/to/config/directory:/config"
      # - "/etc/localtime:/etc/localtime:ro"
    environment:
      - OPENVPN_PROVIDER=MULLVAD
      - OPENVPN_CONFIG=default
      # - OPENVPN_USERNAME=
      # - OPENVPN_PASSWORD=
      - PUID=1000
      - PGID=1000
      - LAN=10.10.30.0/24
    ports:
      - "8055:8080"
    networks:
      - caddy_proxy
    labels:
      caddy: qbittorent.example.com
      caddy.reverse_proxy: "{{upstreams 8080}}"
      caddy.tls: "internal"
      caddy.tls.on_demand:
    cap_add:
      - NET_ADMIN

networks:
  caddy_proxy:
    external: true