version: "3.8"

services:
  radarr:
    image: linuxserver/radarr
    environment:
      PUID: ${RADARR_PUID}
      PGID: ${PGID}
      UMASK: ${UMASK}
      TZ: ${TZ}
    volumes:
      - /home/docker/radarr:/config
      - radarr_data:/data
    networks:
      - proxy
    deploy:
      placement:
        constraints: [node.hostname == vaquita]
      labels:
        caddy: radarr.ant-podz.xyz
        caddy.reverse_proxy: "{{upstreams 7878}}"
        caddy.tls: internal
        caddy.tls.on_demand:

networks:
  proxy:
    external: true

volumes:
  radarr_data:
    driver: local
    driver_opts:
      type: nfs4
      o: ${NFS_CONN}
      device: :/data
