version: "3.8"

services:
  radarr:
    image: linuxserver/radarr
    env_file: .env
    environment:
      PUID: $UID
      PGID: $GID
      TZ: $TZ
    volumes:
      - radarr_config:/config
      - radarr_data:/data
    networks:
      - proxy
    deploy:
      placement:
        constraints: [node.role == worker]
      labels:
        caddy: radarr.lan.com
        caddy.reverse_proxy: "{{upstreams 7878}}"
        caddy.tls: "internal"
        caddy.tls.on_demand:

networks:
  proxy:
    external: true

volumes:
  radarr_config:
    driver: local
    driver_opts:
      type: nfs
      o: $NFS_CONN
      device: :/docker/radarr
  radarr_data:
    driver: local
    driver_opts:
      type: nfs
      o: $NFS_CONN
      device: :/data
