version: '3.8'

services:
  requestrr:
    image: linuxserver/requestrr
    environment:
      PUID: ${REQUESTRR_PUID}
      PGID: ${PGID}
      UMASK: ${UMASK}
      TZ: ${TZ}
    volumes:
      - /home/docker/requestrr:/config
    networks:
      - proxy
    deploy:
      placement:
        constraints: [node.hostname == vaquita]
      labels:
        caddy: requestrr.lan.com
        caddy.reverse_proxy: "{{upstreams 4545}}"
        caddy.tls: "internal"
        caddy.tls.on_demand:

networks:
  proxy:
    external: true
