version: '3.8'

services:
  requestrr:
    image: linuxserver/requestrr
    environment:
      PUID: ${REQUESTRR_PUID}
      PGID: ${PGID}
      UMASK: ${UMASK}
      TZ: ${TZ}
    volumes:
      - requestrr_config:/config
    networks:
      - proxy
    deploy:
      placement:
        constraints: [node.hostname == beluga]
      labels:
        caddy: requestrr.ant-podz.xyz
        caddy.reverse_proxy: "{{upstreams 4545}}"
        caddy.tls: internal
        caddy.tls.on_demand:

networks:
  proxy:
    external: true

volumes:
  requestrr_config:
