version: "3.8"

services:
  sonarr:
    image: linuxserver/sonarr
    environment:
      PUID: ${SONARR_PUID}
      PGID: ${PGID}
      UMASK: ${UMASK}
      TZ: ${TZ}
    volumes:
      - /home/docker/sonarr:/config
      - sonarr_data:/data
    networks:
      - proxy
    deploy:
      placement:
        constraints: [node.hostname == vaquita]
      labels:
        caddy: sonarr.lan.com
        caddy.reverse_proxy: "{{upstreams 8989}}"
        caddy.tls: "internal"
        caddy.tls.on_demand:

networks:
  proxy:
    external: true

volumes:
  sonarr_data:
    driver: local
    driver_opts:
      type: nfs4
      o: ${NFS_CONN}
      device: :/data