version: "3.8"

services:
  sonarr:
    image: linuxserver/sonarr:preview
    env_file: .env
    ports:
      - 8989:8989
    environment:
      PUID: $UID
      PGID: $GID
      TZ: $TZ
      UMASK_SET: 022 #optional
    volumes:
      - config:/config
      - tv:/tv
      - downloads:/downloads
    networks:
      - caddy_proxy
    labels:
      caddy: sonarr.example.com
      caddy.reverse_proxy: "{{upstreams 8989}}"
      caddy.tls: "internal"
      caddy.tls.on_demand:

networks:
  caddy_proxy:
    external: true

#todo
volumes:
  config:
  tv:
  downloads: