version: "3.8"

services:
  sonarr:
    image: linuxserver/sonarr
    env_file: .env
    environment:
      PUID: $UID
      PGID: $GID
      TZ: $TZ
    volumes:
      - sonarr_config:/config
      - sonarr_data:/data
    networks:
      - proxy
    deploy:
      placement:
        constraints: [node.role == worker]
      labels:
        caddy: sonarr.lan.com
        caddy.reverse_proxy: "{{upstreams 8989}}"
        caddy.tls: "internal"
        caddy.tls.on_demand:

networks:
  proxy:
    external: true

volumes:
  sonarr_config:
    driver: local
    driver_opts:
      type: nfs
      o: $NFS_CONN
      device: :/docker/sonarr
  sonarr_data:
    driver: local
    driver_opts:
      type: nfs
      o: $NFS_CONN
      device: :/data