version: "3.8"

services:
  sonarr:
    image: linuxserver/sonarr:preview
    env_file: .env
    environment:
      PUID: $UID
      PGID: $GID
      TZ: $TZ
      UMASK_SET: 022 #optional
    volumes:
      - sonarr_config:/config
      - sonarr_tv:/tv
      - sonarr_downloads:/downloads
    networks:
      - proxy
    labels:
      caddy: sonarr.example.com
      caddy.reverse_proxy: "{{upstreams 8989}}"
      caddy.tls: "internal"
      caddy.tls.on_demand:

networks:
  proxy:
    external: true

volumes:
  sonarr_config:
    driver: local
    driver_opts:
      type: "nfs"
      o: $NFS_CONN
      device: ":/sonarr/config"
  sonarr_tv:
    driver: local
    driver_opts:
      type: "nfs"
      o: $NFS_CONN
      device: ":/sonarr/tv"
  sonarr_downloads:
    driver: local
    driver_opts:
      type: "nfs"
      o: $NFS_CONN
      device: ":/sonarr/downloads"