version: '3.8'

# run using docker-compose and not in swarm :(
services:
  stubby:
    image: anthonyenr1quez/stubby-arm:pi4
    container_name: stubby
    networks:
     - dns
    restart: unless-stopped
  unbound:
    image: anthonyenr1quez/unbound-arm:pi4
    container_name: unbound
    depends_on:
      - "stubby"
    networks:
     - dns
   # volumes:
   #   - ./unbound/a-records.conf:/opt/unbound/etc/unbound/a-records.conf:ro
    restart: unless-stopped

networks:
  dns:
    external: true