version: "3.8"

services:
  transmission-openvpn:
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=0"
    env_file:
      - .env
    environment:
      # - OPENVPN_PROVIDER=
      # - OPENVPN_CONFIG=france TODO
      # - OPENVPN_USERNAME=user
      # - OPENVPN_PASSWORD=pass
      - LOCAL_NETWORK=10.0.2.0/24
      - TRANSMISSION_WEB_UI=transmission-web-control
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      - proxy
    volumes:
      - transmission_config:/data/transmission-home
      - transmission_data:/data/torrents
    deploy:
      placement:
        constraints: [node.hostname == humpback]
      labels:
        caddy: transmission.lan.com
        caddy.reverse_proxy: "{{upstreams 9091}}"
        caddy.tls: "internal"
        caddy.tls.on_demand:

networks:
  proxy:
    external: true

volumes:
  transmission_config:
    driver: local
    driver_opts:
      type: nfs
      o: $NFS_CONN
      device: :/docker/transmission
  transmission_data:
    driver: local
    driver_opts:
      type: nfs
      o: $NFS_CONN
      device: :/data/torrents
      