services:
  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: transmission
    cap_add:
      - NET_ADMIN
    env_file: 
      - .env
    environment:
      - OPENVPN_PROVIDER=MULLVAD
      # - OPENVPN_CONFIG=france
      # - OPENVPN_USERNAME=user
      # - OPENVPN_PASSWORD=pass
      - LOCAL_NETWORK=192.168.1.0/16
    networks:
      - proxy
    volumes:
      - trans_data:/data
    logging:
      driver: json-file
      options:
          max-size: 10m
    ports:
      - '9091:9091'
    labels:
      caddy: transmission.example.com
      caddy.reverse_proxy: "{{upstreams 9091}}"
      caddy.tls: "internal"
      caddy.tls.on_demand:
        
networks:
  proxy:
    external: true