services:
  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: transmission
    cap_add:
      - NET_ADMIN
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=0"
    env_file:
      - .env
    environment:
      - OPENVPN_PROVIDER=MULLVAD
      # - OPENVPN_CONFIG=france
      # - OPENVPN_USERNAME=user
      # - OPENVPN_PASSWORD=pass
      - LOCAL_NETWORK=10.0.2.0/24
    networks:
      - proxy
    volumes:
      - transmission_data:/data
    labels:
      caddy: transmission.example.com
      caddy.reverse_proxy: "{{upstreams 9091}}"
      caddy.tls: "internal"
      caddy.tls.on_demand:

networks:
  proxy:
    external: true

volumes:
  transmission_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: $NFS_CONN
      device: ":/transmission/data"