version: "3.8"

# stubby container has to be running before trying to deploy, healthcheck will not work due to generated config with stubby ip
services:
  unbound:
    image: anthonyenr1quez/unbound-arm
    networks:
     - dns
    deploy:
      placement:
        constraints: [node.hostname == vaquita]

networks:
  dns:
    external: true
    