version: "3.8"

services:
  whoogle-search:
    image: benbusby/whoogle-search:buildx-experimental
    networks:
      - proxy
    deploy:
      placement:
        constraints: [node.role == worker]
      labels:
        caddy: whoogle.example.com
        caddy.reverse_proxy: "{{upstreams 5000}}"
        caddy.tls: "internal"
        caddy.tls.on_demand:

networks:
  proxy:
    external: true