version: "3.8"

services:
  whoogle-search:
    image: benbusby/whoogle-search:buildx-experimental
    networks:
      - proxy
    dns:
      - ${PIHOLE_SERVER_IP}
    deploy:
      placement:
        constraints: [node.hostname == vaquita]
      labels:
        caddy: whoogle.ant-podz.xyz
        caddy.reverse_proxy: "{{upstreams 5000}}"
        caddy.tls: internal
        caddy.tls.on_demand:

networks:
  proxy:
    external: true