version: "3.8"

#TODO https://github.com/benbusby/whoogle-search/issues/117
services:
  whoogle-search:
    image: brightopia/whoogle-search
    networks:
      - proxy
    deploy:
      labels:
        caddy: whoogle.example.com
        caddy.reverse_proxy: "{{upstreams 5000}}"
        caddy.tls: "internal"
        caddy.tls.on_demand:

networks:
  proxy:
    external: true