version: "3.8"

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine-arm32v6
    container_name: caddy
    ports:
      - "80"
      - "443"
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # this volume is needed to keep the certificates
      # otherwise, new ones will be re-issued upon restart
      - caddy_data:/data
    labels: # Global options
      caddy.email: dttztceclomabxpzit@kiabws.online

networks:
  proxy:
    driver: bridge

volumes:
  caddy_data: {}
