version: "3.8"

services:
  whoogle-search:
    image: benbusby/whoogle-search:latest
    container_name: whoogle-search
    ports:
      - 5000:5000
    restart: unless-stopped
    networks:
      - caddy_proxy
    labels:
      caddy: whoogle.example.com
      caddy.reverse_proxy: "{{upstreams 5000}}"
      caddy.tls: "internal"
      caddy.tls.on_demand:

networks:
  caddy_proxy:
    external: true
