version: "3.8"

# http://jell.yfish.us/
# https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/
services:
  plex:
    image: plexinc/pms-docker
    env_file: .env
    ports:
      - 32400:32400
    networks:
      - proxy
    environment:
      - PLEX_UID=1000
      - PLEX_GID=1000
      - PLEX_CLAIM= #optional
      # - 'ALLOWED_NETWORKS=192.168.1.0/24,172.16.0.0/12'
    volumes:
      - /mnt/nas1/docker/plex:/config
      - plex_media:/media
    deploy:
      placement:
        constraints: [node.hostname == humpback]
      labels:
        caddy: plex.lan.com
        caddy.reverse_proxy: "{{upstreams 32400}}"
        caddy.tls: "internal"
        caddy.tls.on_demand:

networks:
  proxy:
    external: true         

volumes:
  plex_media:
    driver: local
    driver_opts:
      type: nfs
      o: $NFS_CONN
      device: :/data/media