version: "3.8"

# plex needs to run with host networking to setup the plex server on inital deploy
# https://www.reddit.com/r/PleX/comments/4qvb8m/plex_media_server_error_setup_is_not_allowed_for/
services:
  plex:
    image: plexinc/pms-docker
    env_file: .env #only for tz
    networks:
      - host
    volumes:
      - /mnt/nas1/docker/plex:/config
    deploy:
      placement:
        constraints: [node.hostname == humpback]

networks:
  host:
    external: true