version: "3.8"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    networks:
      - caddy_proxy
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8053:80/tcp"
      - "8054:443/tcp"
    environment:
      ServerIP: 192.168.1.50
      # PROXY_LOCATION: pihole
      #VIRTUAL_HOST: pihole.homedomain.lan
      # VIRTUAL_PORT: 80
      TZ: 'America/Denver'
      WEBPASSWORD: 'temp123' #TODO secrets
      DNS1: 127.0.0.1
      DNS2: 9.9.9.9
    # Volumes store your data between container upgrades
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmasqd/:/etc/dnsmasq.d/
      # run `touch ./pihole.log` first unless you like errors
      # - ./pihole.log:/var/log/pihole.log
    labels:
      caddy: pihole.example.com
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: "internal"
      caddy.tls.on_demand:

networks:
  caddy_proxy:
    external: true
