version: "3.8"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - AUTO_UPDATE=true #optional
      # - RUN_OPTS=<run options here> #optional
    volumes:
      - jackett-config:/config
      - jackett-downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    labels:
      caddy: jackett.example.com
      caddy.reverse_proxy: "{{upstreams 9117}}"
      caddy.tls: "internal"
      caddy.tls.on_demand:

volumes:
  jackett-config:
  jackett-downloads: