version: "3.8"

# TODO https://github.com/go-gitea/gitea/issues/531
services:
  gitea:
    image: kunde21/gitea-arm
    env_file: .env
    ports:
      - "222:22"
    environment:
      USER_UID: $UID
      USER_GID: $GID
    networks:
      - proxy
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    deploy:
      labels:
        caddy: gitea.lan.com
        caddy.reverse_proxy: "{{upstreams 3000}}"
        caddy.tls: "internal"
        caddy.tls.on_demand:

networks:
  proxy:
    external: true

volumes:
  gitea_data:
    driver: local
    driver_opts:
      type: nfs4
      o: ${NFS_CONN}
      device: :/gitea